config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks
  end

  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, :dependent => :destroy
    validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = List.all
    end

    def show
        @list = List.find(params[:id])
    end    

    def new
        @list = List.new
    end

    def edit
        @list = List.find(params[:id])        
    end

    def update
        @list = List.find(params[:id])

        if @list.update(list_params)
            redirect_to @list
        else
            render 'edit'
        end
    end

    def create
        @list = List.new(list_params)

        if @list.save            
            redirect_to @list
        else
            render 'new'
        end
    end

    def destroy
        @list = List.find(params[:id])
        @list.destroy

        redirect_to lists_path
    end

    private
        def list_params
            params.require(:list).permit(:name)        
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index    
    end

    def create
        @list = List.find(params[:list_id])
        @task = @list.tasks.new(task_params)
        
        if @task.save
            redirect_to @list
        else
            redirect_to :controller => 'lists', :action => 'show', :id => @list.id
        end                
    end   

    def destroy
        @list = List.find(params[:list_id])
        @task = @list.tasks.find(params[:id])

        @task.destroy

        redirect_to list_path(@list)
    end

    private
        def task_params
            params.require(:task).permit(:name, :done)
        end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wunderlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for :list do |l| %>
    <% if @list.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@list.errors.count, "error") %> prohibited
                this list from being saved:
            </h2>
            <ul>
                <% @list.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= l.label :name %><br>
        <%= l.text_field :name %>
    </p>

    <p>
        <%= l.submit %>
    </p>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= form_for :list, url: list_path(@list), method: :patch do |l| %>
    <% if @list.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@list.errors.count, "error") %> prohibited
                this list from being saved:
            </h2>
            <ul>
                <% @list.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= l.label :name %><br>
        <%= l.text_field :name %>
    </p>
 
    <p>
        <%= l.submit %>
    </p>
 
<% end %>
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Hello from index Lists</h1>
<%= link_to 'Make new List', new_list_path %>

<% @lists.each do |l| %>

<h3>    
    <%= link_to l.name, list_path(l) %>    
</h3>    

<% end %>

app/views/lists/new.html.erb
<h1>Create new list</h1>

<% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li> <%= @list.name %> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for :list, url: lists_path do |l| %>
    <p>
        <%= l.label :name %><br>
        <%= l.text_field :name %>
    </p>
  
    <p>
      <%= l.submit %>
    </p>
<% end %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%= link_to 'Edit', edit_list_path %>
<%= link_to 'Destroy', list_path(@list), method: :delete, data: { confirm: 'Are you sure you want to destroy this list?'}%>
<br>
<br>

<h3>Your Tasks:</h3>
<% @list.tasks.each do |t| %>
    <div style="display: flex;">
        <p><%= t.name %></p>  
        <span style="padding-top: 15px; padding-left: 10px;"><%= link_to 'Done', [t.list, t], method: :delete %></span>              
    </div>    
    
<% end %>

<h4 style="text-decoration: underline;">Add Task:</h4>

<%= form_for([@list, @list.tasks.build]) do |l| %>
  <p>
    Task <%= l.label :name %>:
    <br>
    <%= l.text_field :name %>
  </p>
  <p>
    <%= l.submit %>
  </p>
<% end %>

<%= link_to 'Back', lists_path %>